apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: adrian-java-app
  labels:
    app: adrian-java-app
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: adrian-java-app
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
